export const countryCodes = [
    { countryName: "United States", isoCode: "US", mobileCode: "+1" },
    { countryName: "Afghanistan", isoCode: "AF", mobileCode: "+93" },
    { countryName: "Albania", isoCode: "AL", mobileCode: "+355" },
    { countryName: "Algeria", isoCode: "DZ", mobileCode: "+213" },
    { countryName: "American Samoa", isoCode: "AS", mobileCode: "+1-684" },
    { countryName: "Andorra", isoCode: "AD", mobileCode: "+376" },
    { countryName: "Angola", isoCode: "AO", mobileCode: "+244" },
    { countryName: "Anguilla", isoCode: "AI", mobileCode: "+1-264" },
    { countryName: "Antarctica", isoCode: "AQ", mobileCode: "+672" },
    { countryName: "Antigua and Barbuda", isoCode: "AG", mobileCode: "+1-268" },
    { countryName: "Argentina", isoCode: "AR", mobileCode: "+54" },
    { countryName: "Armenia", isoCode: "AM", mobileCode: "+374" },
    { countryName: "Aruba", isoCode: "AW", mobileCode: "+297" },
    { countryName: "Australia", isoCode: "AU", mobileCode: "+61" },
    { countryName: "Austria", isoCode: "AT", mobileCode: "+43" },
    { countryName: "Azerbaijan", isoCode: "AZ", mobileCode: "+994" },
    { countryName: "Bahamas", isoCode: "BS", mobileCode: "+1-242" },
    { countryName: "Bahrain", isoCode: "BH", mobileCode: "+973" },
    { countryName: "Bangladesh", isoCode: "BD", mobileCode: "+880" },
    { countryName: "Barbados", isoCode: "BB", mobileCode: "+1-246" },
    { countryName: "Belarus", isoCode: "BY", mobileCode: "+375" },
    { countryName: "Belgium", isoCode: "BE", mobileCode: "+32" },
    { countryName: "Belize", isoCode: "BZ", mobileCode: "+501" },
    { countryName: "Benin", isoCode: "BJ", mobileCode: "+229" },
    { countryName: "Bermuda", isoCode: "BM", mobileCode: "+1-441" },
    { countryName: "Bhutan", isoCode: "BT", mobileCode: "+975" },
    { countryName: "Bolivia", isoCode: "BO", mobileCode: "+591" },
    { countryName: "Bosnia and Herzegovina", isoCode: "BA", mobileCode: "+387" },
    { countryName: "Botswana", isoCode: "BW", mobileCode: "+267" },
    { countryName: "Brazil", isoCode: "BR", mobileCode: "+55" },
    { countryName: "British Indian Ocean Territory", isoCode: "IO", mobileCode: "+246" },
    { countryName: "British Virgin Islands", isoCode: "VG", mobileCode: "+1-284" },
    { countryName: "Brunei", isoCode: "BN", mobileCode: "+673" },
    { countryName: "Bulgaria", isoCode: "BG", mobileCode: "+359" },
    { countryName: "Burkina Faso", isoCode: "BF", mobileCode: "+226" },
    { countryName: "Burundi", isoCode: "BI", mobileCode: "+257" },
    { countryName: "Cabo Verde", isoCode: "CV", mobileCode: "+238" },
    { countryName: "Cambodia", isoCode: "KH", mobileCode: "+855" },
    { countryName: "Cameroon", isoCode: "CM", mobileCode: "+237" },
    { countryName: "Canada", isoCode: "CA", mobileCode: "+1" },
    { countryName: "Cayman Islands", isoCode: "KY", mobileCode: "+1-345" },
    { countryName: "Central African Republic", isoCode: "CF", mobileCode: "+236" },
    { countryName: "Chad", isoCode: "TD", mobileCode: "+235" },
    { countryName: "Chile", isoCode: "CL", mobileCode: "+56" },
    { countryName: "China", isoCode: "CN", mobileCode: "+86" },
    { countryName: "Christmas Island", isoCode: "CX", mobileCode: "+61" },
    { countryName: "Cocos (Keeling) Islands", isoCode: "CC", mobileCode: "+61" },
    { countryName: "Colombia", isoCode: "CO", mobileCode: "+57" },
    { countryName: "Comoros", isoCode: "KM", mobileCode: "+269" },
    { countryName: "Congo", isoCode: "CG", mobileCode: "+242" },
    { countryName: "Congo, Democratic Republic of the", isoCode: "CD", mobileCode: "+243" },
    { countryName: "Cook Islands", isoCode: "CK", mobileCode: "+682" },
    { countryName: "Costa Rica", isoCode: "CR", mobileCode: "+506" },
    { countryName: "Croatia", isoCode: "HR", mobileCode: "+385" },
    { countryName: "Cuba", isoCode: "CU", mobileCode: "+53" },
    { countryName: "Cyprus", isoCode: "CY", mobileCode: "+357" },
    { countryName: "Czech Republic", isoCode: "CZ", mobileCode: "+420" },
    { countryName: "Denmark", isoCode: "DK", mobileCode: "+45" },
    { countryName: "Djibouti", isoCode: "DJ", mobileCode: "+253" },
    { countryName: "Dominica", isoCode: "DM", mobileCode: "+1-767" },
    { countryName: "Dominican Republic", isoCode: "DO", mobileCode: "+1-809, +1-829, +1-849" },
    { countryName: "Ecuador", isoCode: "EC", mobileCode: "+593" },
    { countryName: "Egypt", isoCode: "EG", mobileCode: "+20" },
    { countryName: "El Salvador", isoCode: "SV", mobileCode: "+503" },
    { countryName: "Equatorial Guinea", isoCode: "GQ", mobileCode: "+240" },
    { countryName: "Eritrea", isoCode: "ER", mobileCode: "+291" },
    { countryName: "Estonia", isoCode: "EE", mobileCode: "+372" },
    { countryName: "Eswatini", isoCode: "SZ", mobileCode: "+268" },
    { countryName: "Ethiopia", isoCode: "ET", mobileCode: "+251" },
    { countryName: "Fiji", isoCode: "FJ", mobileCode: "+679" },
    { countryName: "Finland", isoCode: "FI", mobileCode: "+358" },
    { countryName: "France", isoCode: "FR", mobileCode: "+33" },
    { countryName: "Gabon", isoCode: "GA", mobileCode: "+241" },
    { countryName: "Gambia", isoCode: "GM", mobileCode: "+220" },
    { countryName: "Georgia", isoCode: "GE", mobileCode: "+995" },
    { countryName: "Germany", isoCode: "DE", mobileCode: "+49" },
    { countryName: "Ghana", isoCode: "GH", mobileCode: "+233" },
    { countryName: "Greece", isoCode: "GR", mobileCode: "+30" },
    { countryName: "Greenland", isoCode: "GL", mobileCode: "+299" },
    { countryName: "Grenada", isoCode: "GD", mobileCode: "+1-473" },
    { countryName: "Guam", isoCode: "GU", mobileCode: "+1-671" },
    { countryName: "Guatemala", isoCode: "GT", mobileCode: "+502" },
    { countryName: "Guernsey", isoCode: "GG", mobileCode: "+44" },
    { countryName: "Guinea", isoCode: "GN", mobileCode: "+224" },
    { countryName: "Guinea-Bissau", isoCode: "GW", mobileCode: "+245" },
    { countryName: "Guyana", isoCode: "GY", mobileCode: "+592" },
    { countryName: "Haiti", isoCode: "HT", mobileCode: "+509" },
    { countryName: "Honduras", isoCode: "HN", mobileCode: "+504" },
    { countryName: "Hong Kong", isoCode: "HK", mobileCode: "+852" },
    { countryName: "Hungary", isoCode: "HU", mobileCode: "+36" },
    { countryName: "Iceland", isoCode: "IS", mobileCode: "+354" },
    { countryName: "India", isoCode: "IN", mobileCode: "+91" },
    { countryName: "Indonesia", isoCode: "ID", mobileCode: "+62" },
    { countryName: "Iran", isoCode: "IR", mobileCode: "+98" },
    { countryName: "Iraq", isoCode: "IQ", mobileCode: "+964" },
    { countryName: "Ireland", isoCode: "IE", mobileCode: "+353" },
    { countryName: "Israel", isoCode: "IL", mobileCode: "+972" },
    { countryName: "Italy", isoCode: "IT", mobileCode: "+39" },
    { countryName: "Jamaica", isoCode: "JM", mobileCode: "+1-876" },
    { countryName: "Japan", isoCode: "JP", mobileCode: "+81" },
    { countryName: "Jersey", isoCode: "JE", mobileCode: "+44" },
    { countryName: "Jordan", isoCode: "JO", mobileCode: "+962" },
    { countryName: "Kazakhstan", isoCode: "KZ", mobileCode: "+7" },
    { countryName: "Kenya", isoCode: "KE", mobileCode: "+254" },
    { countryName: "Kiribati", isoCode: "KI", mobileCode: "+686" },
    { countryName: "Korea, North", isoCode: "KP", mobileCode: "+850" },
    { countryName: "Korea, South", isoCode: "KR", mobileCode: "+82" },
    { countryName: "Kuwait", isoCode: "KW", mobileCode: "+965" },
    { countryName: "Kyrgyzstan", isoCode: "KG", mobileCode: "+996" },
    { countryName: "Laos", isoCode: "LA", mobileCode: "+856" },
    { countryName: "Latvia", isoCode: "LV", mobileCode: "+371" },
    { countryName: "Lebanon", isoCode: "LB", mobileCode: "+961" },
    { countryName: "Lesotho", isoCode: "LS", mobileCode: "+266" },
    { countryName: "Liberia", isoCode: "LR", mobileCode: "+231" },
    { countryName: "Libya", isoCode: "LY", mobileCode: "+218" },
    { countryName: "Liechtenstein", isoCode: "LI", mobileCode: "+423" },
    { countryName: "Lithuania", isoCode: "LT", mobileCode: "+370" },
    { countryName: "Luxembourg", isoCode: "LU", mobileCode: "+352" },
    { countryName: "Macau", isoCode: "MO", mobileCode: "+853" },
    { countryName: "Madagascar", isoCode: "MG", mobileCode: "+261" },
    { countryName: "Malawi", isoCode: "MW", mobileCode: "+265" },
    { countryName: "Malaysia", isoCode: "MY", mobileCode: "+60" },
    { countryName: "Maldives", isoCode: "MV", mobileCode: "+960" },
    { countryName: "Mali", isoCode: "ML", mobileCode: "+223" },
    { countryName: "Malta", isoCode: "MT", mobileCode: "+356" },
    { countryName: "Marshall Islands", isoCode: "MH", mobileCode: "+692" },
    { countryName: "Martinique", isoCode: "MQ", mobileCode: "+596" },
    { countryName: "Mauritania", isoCode: "MR", mobileCode: "+222" },
    { countryName: "Mauritius", isoCode: "MU", mobileCode: "+230" },
    { countryName: "Mayotte", isoCode: "YT", mobileCode: "+262" },
    { countryName: "Mexico", isoCode: "MX", mobileCode: "+52" },
    { countryName: "Micronesia", isoCode: "FM", mobileCode: "+691" },
    { countryName: "Moldova", isoCode: "MD", mobileCode: "+373" },
    { countryName: "Monaco", isoCode: "MC", mobileCode: "+377" },
    { countryName: "Mongolia", isoCode: "MN", mobileCode: "+976" },
    { countryName: "Montenegro", isoCode: "ME", mobileCode: "+382" },
    { countryName: "Montserrat", isoCode: "MS", mobileCode: "+1-664" },
    { countryName: "Morocco", isoCode: "MA", mobileCode: "+212" },
    { countryName: "Mozambique", isoCode: "MZ", mobileCode: "+258" },
    { countryName: "Myanmar", isoCode: "MM", mobileCode: "+95" },
    { countryName: "Namibia", isoCode: "NA", mobileCode: "+264" },
    { countryName: "Nauru", isoCode: "NR", mobileCode: "+674" },
    { countryName: "Nepal", isoCode: "NP", mobileCode: "+977" },
    { countryName: "Netherlands", isoCode: "NL", mobileCode: "+31" },
    { countryName: "New Caledonia", isoCode: "NC", mobileCode: "+687" },
    { countryName: "New Zealand", isoCode: "NZ", mobileCode: "+64" },
    { countryName: "Nicaragua", isoCode: "NI", mobileCode: "+505" },
    { countryName: "Niger", isoCode: "NE", mobileCode: "+227" },
    { countryName: "Nigeria", isoCode: "NG", mobileCode: "+234" },
    { countryName: "Niue", isoCode: "NU", mobileCode: "+683" },
    { countryName: "Norfolk Island", isoCode: "NF", mobileCode: "+672" },
    { countryName: "North Macedonia", isoCode: "MK", mobileCode: "+389" },
    { countryName: "Northern Mariana Islands", isoCode: "MP", mobileCode: "+1-670" },
    { countryName: "Norway", isoCode: "NO", mobileCode: "+47" },
    { countryName: "Oman", isoCode: "OM", mobileCode: "+968" },
    { countryName: "Pakistan", isoCode: "PK", mobileCode: "+92" },
    { countryName: "Palau", isoCode: "PW", mobileCode: "+680" },
    { countryName: "Panama", isoCode: "PA", mobileCode: "+507" },
    { countryName: "Papua New Guinea", isoCode: "PG", mobileCode: "+675" },
    { countryName: "Paraguay", isoCode: "PY", mobileCode: "+595" },
    { countryName: "Peru", isoCode: "PE", mobileCode: "+51" },
    { countryName: "Philippines", isoCode: "PH", mobileCode: "+63" },
    { countryName: "Pitcairn Islands", isoCode: "PN", mobileCode: "+64" },
    { countryName: "Poland", isoCode: "PL", mobileCode: "+48" },
    { countryName: "Portugal", isoCode: "PT", mobileCode: "+351" },
    { countryName: "Puerto Rico", isoCode: "PR", mobileCode: "+1-787, +1-939" },
    { countryName: "Qatar", isoCode: "QA", mobileCode: "+974" },
    { countryName: "Romania", isoCode: "RO", mobileCode: "+40" },
    { countryName: "Russia", isoCode: "RU", mobileCode: "+7" },
    { countryName: "Rwanda", isoCode: "RW", mobileCode: "+250" },
    { countryName: "Reunion", isoCode: "RE", mobileCode: "+262" },
    { countryName: "Saint Barthelemy", isoCode: "BL", mobileCode: "+590" },
    { countryName: "Saint Helena", isoCode: "SH", mobileCode: "+290" },
    { countryName: "Saint Kitts and Nevis", isoCode: "KN", mobileCode: "+1-869" },
    { countryName: "Saint Lucia", isoCode: "LC", mobileCode: "+1-758" },
    { countryName: "Saint Martin", isoCode: "MF", mobileCode: "+590" },
    { countryName: "Saint Pierre and Miquelon", isoCode: "PM", mobileCode: "+508" },
    { countryName: "Saint Vincent and the Grenadines", isoCode: "VC", mobileCode: "+1-784" },
    { countryName: "Samoa", isoCode: "WS", mobileCode: "+685" },
    { countryName: "San Marino", isoCode: "SM", mobileCode: "+378" },
    { countryName: "Sao Tome and Principe", isoCode: "ST", mobileCode: "+239" },
    { countryName: "Saudi Arabia", isoCode: "SA", mobileCode: "+966" },
    { countryName: "Senegal", isoCode: "SN", mobileCode: "+221" },
    { countryName: "Serbia", isoCode: "RS", mobileCode: "+381" },
    { countryName: "Seychelles", isoCode: "SC", mobileCode: "+248" },
    { countryName: "Sierra Leone", isoCode: "SL", mobileCode: "+232" },
    { countryName: "Singapore", isoCode: "SG", mobileCode: "+65" },
    { countryName: "Sint Eustatius", isoCode: "BQ", mobileCode: "+599" },
    { countryName: "Sint Maarten", isoCode: "SX", mobileCode: "+1-721" },
    { countryName: "Slovakia", isoCode: "SK", mobileCode: "+421" },
    { countryName: "Slovenia", isoCode: "SI", mobileCode: "+386" },
    { countryName: "Solomon Islands", isoCode: "SB", mobileCode: "+677" },
    { countryName: "Somalia", isoCode: "SO", mobileCode: "+252" },
    { countryName: "South Africa", isoCode: "ZA", mobileCode: "+27" },
    { countryName: "South Georgia and the South Sandwich Islands", isoCode: "GS", mobileCode: "+500" },
    { countryName: "South Sudan", isoCode: "SS", mobileCode: "+211" },
    { countryName: "Spain", isoCode: "ES", mobileCode: "+34" },
    { countryName: "Sri Lanka", isoCode: "LK", mobileCode: "+94" },
    { countryName: "Sudan", isoCode: "SD", mobileCode: "+249" },
    { countryName: "Suriname", isoCode: "SR", mobileCode: "+597" },
    { countryName: "Svalbard", isoCode: "SJ", mobileCode: "+47" },
    { countryName: "Sweden", isoCode: "SE", mobileCode: "+46" },
    { countryName: "Switzerland", isoCode: "CH", mobileCode: "+41" },
    { countryName: "Syria", isoCode: "SY", mobileCode: "+963" },
    { countryName: "Taiwan", isoCode: "TW", mobileCode: "+886" },
    { countryName: "Tajikistan", isoCode: "TJ", mobileCode: "+992" },
    { countryName: "Tanzania", isoCode: "TZ", mobileCode: "+255" },
    { countryName: "Thailand", isoCode: "TH", mobileCode: "+66" },
    { countryName: "Timor-Leste", isoCode: "TL", mobileCode: "+670" },
    { countryName: "Togo", isoCode: "TG", mobileCode: "+228" },
    { countryName: "Tokelau", isoCode: "TK", mobileCode: "+690" },
    { countryName: "Tonga", isoCode: "TO", mobileCode: "+676" },
    { countryName: "Trinidad and Tobago", isoCode: "TT", mobileCode: "+1-868" },
    { countryName: "Tunisia", isoCode: "TN", mobileCode: "+216" },
    { countryName: "Turkey", isoCode: "TR", mobileCode: "+90" },
    { countryName: "Turkmenistan", isoCode: "TM", mobileCode: "+993" },
    { countryName: "Tuvalu", isoCode: "TV", mobileCode: "+688" },
    { countryName: "Uganda", isoCode: "UG", mobileCode: "+256" },
    { countryName: "Ukraine", isoCode: "UA", mobileCode: "+380" },
    { countryName: "United Arab Emirates", isoCode: "AE", mobileCode: "+971" },
    { countryName: "United Kingdom", isoCode: "GB", mobileCode: "+44" },
    { countryName: "Uruguay", isoCode: "UY", mobileCode: "+598" },
    { countryName: "Uzbekistan", isoCode: "UZ", mobileCode: "+998" },
    { countryName: "Vanuatu", isoCode: "VU", mobileCode: "+678" },
    { countryName: "Vatican City", isoCode: "VA", mobileCode: "+379" },
    { countryName: "Venezuela", isoCode: "VE", mobileCode: "+58" },
    { countryName: "Vietnam", isoCode: "VN", mobileCode: "+84" },
    { countryName: "Wallis and Futuna", isoCode: "WF", mobileCode: "+681" },
    { countryName: "Western Sahara", isoCode: "EH", mobileCode: "+212" },
    { countryName: "Yemen", isoCode: "YE", mobileCode: "+967" },
    { countryName: "Zambia", isoCode: "ZM", mobileCode: "+260" },
    { countryName: "Zimbabwe", isoCode: "ZW", mobileCode: "+263" }
  ]
  