export const permission_constants = {
    PATIENT: 'Patient',
    PATIENTPAYMENT: 'PatientPayment',
    STAFF: 'Staff',
    EXERCISE: 'Exercise',
    EXERCISEAPPROVEREJECT: 'ExerciseApproveReject',
    PATIENTPLAN: 'PatientPlan',
    PATIENTREPORTS: 'PatientReports',
    DASHBOARD: 'Dashboard',
    EXERCISEUPLOAD: 'ExerciseUpload',
    EXERCISEACTIVETAB: 'ExerciseActiveTab', 
    EXERCISEAPPROVALTAB: 'ExerciseApprovalTab',
    EXERCISEDRAFTTAB: 'ExerciseDraftTab',
    EXERCISEREJECTEDTTAB: 'ExerciseRejectedTab',
    PATIENTACTIVETAB: 'PatientActiveTab',
    PATIENTHEALTHISSUETAB: 'PatientHealthIssueTab',
    PATIENTPAYMENTTAB: 'PatientPaymentTab',
    CHAT: 'Chat',
    SETTINGS: 'Settings',
};